// <auto-generated />
using System;
using ECommerce.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommerce.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250429135412_TabelasPedido")]
    partial class TabelasPedido
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Clientes.ClienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("INTEGER")
                        .HasColumnName("cpf");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<long>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("INTEGER")
                        .HasColumnName("telefone");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.ToTable("cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = 11111111111L,
                            Endereco = "Rua Teste, 123",
                            Nome = "Cliente Admin",
                            Telefone = 0L
                        },
                        new
                        {
                            Id = 2L,
                            Cpf = 22222222222L,
                            Endereco = "Rua Teste, 124",
                            Nome = "Cliente Comum",
                            Telefone = 0L
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<DateTime>("DataPedido")
                        .HasColumnType("TEXT")
                        .HasColumnName("data_pedido");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("valor_total");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("DataPedido");

                    b.HasIndex("Status");

                    b.ToTable("pedido", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ClienteId = 1L,
                            DataPedido = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Aguardando Pagamento",
                            ValorTotal = 0m
                        },
                        new
                        {
                            Id = 2L,
                            ClienteId = 2L,
                            DataPedido = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Enviado",
                            ValorTotal = 0m
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity+PedidoItem", b =>
                {
                    b.Property<long>("PedidoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("pedido_id");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("PedidoId1")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco_unitario");

                    b.Property<long>("ProdutoId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("produto_id");

                    b.Property<int>("Quantidade")
                        .HasColumnType("INTEGER")
                        .HasColumnName("quantidade");

                    b.HasKey("PedidoId", "Id");

                    b.HasIndex("PedidoId1");

                    b.HasIndex("ProdutoId");

                    b.ToTable("pedido_item", (string)null);
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Produtos.ProdutoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("descricao");

                    b.Property<int>("Estoque")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estoque");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<decimal>("Preco")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("preco");

                    b.HasKey("Id");

                    b.ToTable("produto", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Descricao = "Descrição do Produto Inicial",
                            Estoque = 50,
                            Nome = "Produto Inicial",
                            Preco = 99.90m
                        },
                        new
                        {
                            Id = 2L,
                            Descricao = "Produto com estoque maior",
                            Estoque = 100,
                            Nome = "Produto Extra",
                            Preco = 49.90m
                        });
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity", b =>
                {
                    b.HasOne("ECommerce.Domain.Aggregates.Clientes.ClienteEntity", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity+PedidoItem", b =>
                {
                    b.HasOne("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity", null)
                        .WithMany("Itens")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity", "Pedido")
                        .WithMany()
                        .HasForeignKey("PedidoId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommerce.Domain.Aggregates.Produtos.ProdutoEntity", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("ECommerce.Domain.Aggregates.Pedidos.PedidoEntity", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
