// <auto-generated />
using System;
using ECommerce.Infrastructure.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaculdadeXPE.ECommerceOnline.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250427013740_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("FaculdadeXPE.ECommerceOnline.Domain.Aggregates.Clientes.ClienteEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<long>("Cpf")
                        .HasMaxLength(11)
                        .HasColumnType("INTEGER")
                        .HasColumnName("cpf");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("endereco");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("Nome");

                    b.Property<long>("Telefone")
                        .HasMaxLength(15)
                        .HasColumnType("INTEGER")
                        .HasColumnName("telefone");

                    b.Property<long>("UsuarioId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("cliente", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Cpf = 11111111111L,
                            Endereco = "Rua Teste, 123",
                            Nome = "Cliente Admin",
                            Telefone = 0L,
                            UsuarioId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Cpf = 22222222222L,
                            Endereco = "Rua Teste, 124",
                            Nome = "Cliente Comum",
                            Telefone = 0L,
                            UsuarioId = 2L
                        });
                });

            modelBuilder.Entity("FaculdadeXPE.ECommerceOnline.Domain.Aggregates.Usuarios.UsuarioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("DataCriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("data_criado")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("login");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nome");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("senha");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            DataCriado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "admin",
                            Nome = "Usuário Administrador",
                            Senha = "123456"
                        },
                        new
                        {
                            Id = 2L,
                            DataCriado = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Login = "comum",
                            Nome = "Usuário Comum",
                            Senha = "123456"
                        });
                });

            modelBuilder.Entity("FaculdadeXPE.ECommerceOnline.Domain.Aggregates.Clientes.ClienteEntity", b =>
                {
                    b.HasOne("FaculdadeXPE.ECommerceOnline.Domain.Aggregates.Usuarios.UsuarioEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
